name: Deploy to Fly.io

on:
  push:
    branches: [main]  # o master, según tu repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy App
      run: flyctl deploy --app noti-meli-bot --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
